name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        env:
          CI: true
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
          RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
          NEXT_PUBLIC_RAZORPAY_KEY_ID: ${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        run: npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
          RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
          NEXT_PUBLIC_RAZORPAY_KEY_ID: ${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

          # Create .env file
          echo "MONGODB_URI=\"$MONGODB_URI\"
          JWT_SECRET=\"$JWT_SECRET\"
          NEXTAUTH_SECRET=\"$NEXTAUTH_SECRET\"
          NEXTAUTH_URL=\"$NEXTAUTH_URL\"
          RAZORPAY_KEY_ID=\"$RAZORPAY_KEY_ID\"
          RAZORPAY_KEY_SECRET=\"$RAZORPAY_KEY_SECRET\"
          NEXT_PUBLIC_RAZORPAY_KEY_ID=\"$NEXT_PUBLIC_RAZORPAY_KEY_ID\"
          GOOGLE_AI_API_KEY=\"$GOOGLE_AI_API_KEY\"
          ADMIN_EMAIL=\"$ADMIN_EMAIL\"
          ADMIN_PASSWORD=\"$ADMIN_PASSWORD\"
          LINKEDIN_CLIENT_ID=\"$LINKEDIN_CLIENT_ID\"
          LINKEDIN_CLIENT_SECRET=\"$LINKEDIN_CLIENT_SECRET\"
          NEXT_PUBLIC_APP_URL=\"$NEXT_PUBLIC_APP_URL\"" > .env

          # Copy the built application and .env
          ssh -i private_key ${USER}@${HOST} 'mkdir -p ~/phantomwriter'
          rsync -avz --exclude 'node_modules' --exclude '.git' -e "ssh -i private_key" ./ ${USER}@${HOST}:~/phantomwriter/

          # Kill existing Node.js process if running
          ssh -i private_key ${USER}@${HOST} 'pkill -f "node server.js" || true'

          # Start the Next.js application
          ssh -i private_key ${USER}@${HOST} 'cd ~/phantomwriter && npm install --production && nohup npm start > app.log 2>&1 &'

          rm -f private_key
